push @output, "Generated by Microsoft (R) HLSL Shader Compiler 9.27.952.3022																								; LINEINFO(passthrough_vs20.vsh)(2)\n";
push @output, "fxc /T vs_2_0 /Fc passthrough_vs20.vsh																								; LINEINFO(passthrough_vs20.vsh)(4)\n";
push @output, "D:\Coding\OverlordMod\src\materialsystem\stdshaders\passthrough_vs20.fxc																								; LINEINFO(passthrough_vs20.vsh)(5)\n";
    push @output, "    vs_2_0																								; LINEINFO(passthrough_vs20.vsh)(7)\n";
    push @output, "    dcl_position v0																								; LINEINFO(passthrough_vs20.vsh)(8)\n";
    push @output, "    dcl_texcoord v1																								; LINEINFO(passthrough_vs20.vsh)(9)\n";
    push @output, "    mov oPos, v0																								; LINEINFO(passthrough_vs20.vsh)(10)\n";
    push @output, "    mov oT0.xy, v1																								; LINEINFO(passthrough_vs20.vsh)(11)\n";
push @output, "approximately 2 instruction slots used																								; LINEINFO(passthrough_vs20.vsh)(13)\n";
