//
// Generated by Microsoft (R) HLSL Shader Compiler 9.27.952.3022
//
//   fxc /T vs_2_0 /Fc passthrough_vs20.vsh
//    D:\Coding\OverlordMod\src\materialsystem\stdshaders\passthrough_vs20.fxc
//
    vs_2_0
    dcl_position v0
    dcl_texcoord v1
    mov oPos, v0
    mov oT0.xy, v1

// approximately 2 instruction slots used
